# Generated by Django 3.1.7 on 2021-03-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210314_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='fingerprint',
            name='user',
            field=models.BooleanField(default=True),
        ),
    ]
