# Generated by Django 3.1.7 on 2021-03-14 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_fingerprint_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fingerprint',
        ),
    ]
